export const surpriseMePrompts = [
  'A steampunk owl with mechanical wings perched on a glowing gear tree, digital art',
  'A cyberpunk monk meditating on a skyscraper rooftop surrounded by holograms',
  'A fantasy elf city floating above clouds with waterfalls pouring into the sky, matte painting',
  'An underwater jazz band of octopuses and jellyfish, colorful digital illustration',
  'A futuristic samurai battling robotic ninjas in Neo-Tokyo, concept art',
  'An astronaut playing violin on the moon under the Earthrise, hyper-realistic',
  'A magical deer with glowing antlers in an enchanted forest at night, fantasy art',
  'A robot gardener tending to alien plants in a glass dome on Mars, sci-fi style',
  'A surreal scene of melting skyscrapers in a desert, Salvador Dali inspired',
  'A medieval knight riding a giant beetle through a misty swamp, dark fantasy',
  'A 1920s noir detective made of shadow walking through a rainy alley',
  'A Viking ship sailing across a sky made of stars and galaxies, oil painting',
  'A cat cafe run entirely by cats in business suits, whimsical cartoon',
  'A haunted library with floating books and ghost librarians, gothic horror',
  'A giant koi fish flying over a futuristic Chinese city, cyber-oriental fusion',
  'A magical bakery with animated pastries baking themselves, cozy fantasy',
  'A tribal alien riding a solar-powered beast across a desert of crystals',
  'A modern witch brewing potions in a high-tech kitchen, contemporary fantasy',
  'A jungle temple covered in vines and guarded by giant stone monkeys',
  'A retro 80s arcade machine that opens a portal to another universe',
  'A winter village where each house floats like balloons, magical realism',
  'A time-traveling explorer landing in ancient Egypt with a holographic map',
  'A phoenix rising from a galaxy core, cosmic firebird concept',
  'A tiny robot chef making sushi inside a wristwatch kitchen',
  'A celestial courtroom where planets are on trial, surreal science fiction',
  'A painter painting planets on a cosmic canvas, ultra HD fantasy art',
  'A dog detective solving mysteries in a neon-lit city, animated film style',
  'A tea ceremony held by forest spirits under glowing cherry blossoms',
  'A spaceship built entirely out of books flying through space',
  'A city run by sentient fungi, mycelium towers and glowing spores',
  'An underwater palace ruled by jellyfish kings, iridescent illustration',
  'A mechanical dragon flying above a dieselpunk battlefield',
  'An enchanted mirror showing alternate versions of the viewer, fantasy style',
  'A group of aliens playing cricket in a zero-gravity field, cartoon render',
  'A robotic hummingbird pollinating cybernetic flowers in a future garden',
  'A dreamscape where people walk on clouds with giant koi swimming beneath',
  'A warlock casting spells through a virtual keyboard, fantasy cyberpunk mashup',
  'A sky train pulled by mechanical birds flying over a neon city',
  'A retro astronaut driving a convertible on Saturn’s rings',
  'A post-apocalyptic playground overrun with plant life and wild animals',
  'A royal ball attended by dinosaurs in Victorian attire, animated style',
  'A martial artist made of stone breaking through a digital wall, stylized concept',
  'A magical storm frozen in time above a floating island',
  'A snow globe containing a live galaxy spinning in real time',
  'A circus in space with zero-gravity performers and floating tents',
  'A rainforest filled with bio-luminescent dragons curled around trees',
  'A humanoid tree giving a TED talk to woodland creatures, whimsical art',
  'A mythical train powered by moonlight crossing a sky bridge at night',
];
